service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::tyres-shop-import-service"
    - Effect: "Allow"
      Action: "s3:*"
      Resource:
        - "arn:aws:s3:::tyres-shop-import-service/*"

plugins:
  - serverless-webpack
  - serverless-auto-swagger

package:
  individually: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  autoswagger:
    title: 'import-service-documentation'
    apiType: 'http'
    basePath: '/dev'

functions:
  importProductsFile:
    handler: handlers/importProductsFile.importProductsFile
    events:
      - http:
          method: 'get'
          path: 'import'
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: tyres-shop-import-service
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
